### ISSUE TITLE
could it ignore IRC channel notice messages?

### ISSUE THREAD

**Issue by awaxa** [dosman711/lita-web-title#13]
I have a few GitHub repositories configured to send _notice_ messages instead of normal messages to an operations IRC channel for repository events.  Could `lita-web-title` be configured to ignore IRC notice messages instead of adding worthless noise in this case?  I worry that it may not be able to determine the type of IRC message since that's handled by an abstraction in the lita framework.

```
11:09:05 <github> [settings] awaxa created remove_dsharp (+1 new commit): http://git.io/v8Vj7
11:09:05 <github> settings/remove_dsharp 65723ed Greg Kitson: remove dsharpdiabetes.com, they shut down
11:09:05 <diabot> remove dsharpdiabetes.com, they shut down · reddit-diabetes/settings@65723ed · GitHub
11:09:25 <github> [settings] awaxa opened pull request #6: remove dsharpdiabetes.com, they shut down (master...remove_dsharp) http://git.io/v8Vjx
11:09:26 <diabot> remove dsharpdiabetes.com, they shut down by awaxa · Pull Request #6 · reddit-diabetes/settings · GitHub
11:09:35 <github> [settings] awaxa closed pull request #6: remove dsharpdiabetes.com, they shut down (master...remove_dsharp) http://git.io/v8Vjx
11:09:36 <diabot> remove dsharpdiabetes.com, they shut down by awaxa · Pull Request #6 · reddit-diabetes/settings · GitHub
```

**Comment by liz-baker** [comment]
Turns out that this was not a notice message, but a message from a not-in-room user. Will still probably make a change to ignore those messages as well as it could lead to spamming a channel.

**Comment by awaxa** [comment]
Pardon me, my IRC notification was misconfigured to send regular messages instead of notice messages.  Feel free to close this.

Allowing messages from users who are not joined is controlled by channel mode `-n`, so I think it's probably out of scope for this plugin.

**Comment by liz-baker** [comment]
Closing issue per comment above
